# Generated by Django 3.0.2 on 2021-01-22 12:19

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YesNoBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('yes_button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('yes_button_bg_color', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('no_button_text', models.CharField(blank=True, max_length=70, null=True)),
                ('no_button_bg_color', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('thank_you_toggler', models.BooleanField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
