# Generated by Django 3.0.2 on 2021-01-22 12:55

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockDownApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yesnobar',
            name='no_button_bg_color',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black')], default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='yesnobar',
            name='yes_button_bg_color',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black')], default='#FFFFFF', max_length=18),
        ),
    ]
